name: EYA_KURUM
description: "Engelsiz Yaşam Platformu Kurum Uygulaması"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  page_transition: ^2.1.0
  image_picker: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  dot_navigation_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_storage: ^11.6.9
  permission_handler: ^11.3.1
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^4.2.1
  video_player: ^2.8.6
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.2
  shared_preferences: ^2.2.3
  unicons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/eya/
 