name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  page_transition: ^2.1.0
  image_picker: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  dot_navigation_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_storage: ^11.6.9
  geocoder2: ^1.4.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter_web: ^0.5.6+2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - lib/images/burgers/
    - lib/images/sides/
    - lib/images/salads/
    - lib/images/drinks/
    - lib/images/desserts/
    - lib/images/eya/
