name: EYA
description: "Engelsiz Yaşam Platformu"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_credit_card: ^4.0.1
  intl: ^0.19.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  page_transition: ^2.1.0
  image_picker: ^1.0.8
  animated_bottom_navigation_bar: ^1.3.3
  dot_navigation_bar: ^1.0.2
  curved_navigation_bar: ^1.0.3
  firebase_storage: ^11.6.9
  geocoder2: ^1.4.0
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_maps_flutter_web: ^0.5.6+2
  permission_handler: ^11.3.1
  flutter_image_slideshow: ^0.1.6
  carousel_slider: ^4.2.1
  video_player: ^2.8.6
  url_launcher: ^6.2.6
  unicons: any
  image_picker_for_web: ^3.0.4
  video_player_web: ^2.3.0
  image_picker_web: ^3.1.1
  chewie: ^1.8.1
  file_picker: ^8.0.3
  flutter_svg: ^2.0.9
  uuid: ^4.4.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.3
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "lib/images/eya/logo.png" 
  android: true
  ios: true
  web: true

flutter:

  

  uses-material-design: true

  assets:
    - lib/images/eya/
