// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgsrfrf8gf9IG3rDRH0k4JooQ3YzxKaEc',
    appId: '1:607045222348:web:2d0699974bd738c49e6769',
    messagingSenderId: '607045222348',
    projectId: 'eyaapp-6595d',
    authDomain: 'eyaapp-6595d.firebaseapp.com',
    databaseURL: 'https://eyaapp-6595d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyaapp-6595d.appspot.com',
    measurementId: 'G-HM8GQ2HNKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXxkpOjviYjtTs96v9lbYf36YSD4nq7DQ',
    appId: '1:607045222348:android:0b851873f097b4b39e6769',
    messagingSenderId: '607045222348',
    projectId: 'eyaapp-6595d',
    databaseURL: 'https://eyaapp-6595d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyaapp-6595d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8mWZDHF0sKbAJ0ROsLffS1TK-HKy520',
    appId: '1:607045222348:ios:ac23f5b9771aa9b69e6769',
    messagingSenderId: '607045222348',
    projectId: 'eyaapp-6595d',
    databaseURL: 'https://eyaapp-6595d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyaapp-6595d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8mWZDHF0sKbAJ0ROsLffS1TK-HKy520',
    appId: '1:607045222348:ios:ac23f5b9771aa9b69e6769',
    messagingSenderId: '607045222348',
    projectId: 'eyaapp-6595d',
    databaseURL: 'https://eyaapp-6595d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyaapp-6595d.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgsrfrf8gf9IG3rDRH0k4JooQ3YzxKaEc',
    appId: '1:607045222348:web:afd74a476ddc98849e6769',
    messagingSenderId: '607045222348',
    projectId: 'eyaapp-6595d',
    authDomain: 'eyaapp-6595d.firebaseapp.com',
    databaseURL: 'https://eyaapp-6595d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eyaapp-6595d.appspot.com',
    measurementId: 'G-D0PZJZLD44',
  );

}